# File    : meson.build
# Purpose : Declares the sources and subdirs for this folder
# Author  : Martin Rizzo | <martinrizzo@gmail.com>
# Date    : Nov 6, 2025
# Repo    : https://github.com/martin-rizzo/TensorInfo
# License : MIT
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#subdir('<none>')
sources += files(
    'gguf' / 'gguf.cpp',
    'dtype.cpp',
    'metadata.cpp',
    'metavalue.cpp',
    'shape.cpp',
    'storagetype.cpp',
    'tensorinfo.cpp',
    'tensormap_gguf.cpp',
    'tensormap_safetensors.cpp',
    'tensormap.cpp',
    'tensortree.cpp',
    'unnamedtensorinfo.cpp'
)
