# File    : meson.build
# Purpose : Declares the sources and subdirs for this folder
# Author  : Martin Rizzo | <martinrizzo@gmail.com>
# Date    : Nov 6, 2025
# Repo    : https://github.com/martin-rizzo/TensorInfo
# License : MIT
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#subdir('<none>')
sources += files(
    'tensorinfo.cpp',
    'tensormap.cpp',
    'tensortree.cpp'
)
