# File    : meson.build
# Purpose : Declares the public headers of the library
# Author  : Martin Rizzo | <martinrizzo@gmail.com>
# Date    : Nov 7, 2025
# Repo    : https://github.com/martin-rizzo/TensorInfo
# License : MIT
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

public_headers += files(
    'common.h',
    'dtype.h',
    'metadata.h',
    'metavariant.h',
    'readerror.h',
    'shape.h',
    'sortby.h',
    'storagetype.h',
    'tensorinfo.h',
    'tensormap.h',
    'tensortree.h',
    'tensortreenode.h',
    'unnamedtensorinfo.h',
)
